services:
  cdc-agents-stream-db:
    image: localhost:5001/postgres-pgvector-15
    container_name: cdc-agents-stream-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5488:5432"
    volumes:
      - /Users/hayde/db/cdc-agents-subscriber/data:/var/lib/postgresql/data

  cdc-agents-stream-db-sub:
    image: localhost:5001/postgres-pgvector-15
    container_name: cdc-agents-stream-db-sub
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5487:5432"
    volumes:
      - cdc-agents-stream-test-sub:/var/lib/postgresql/data

volumes:
  cdc-agents-stream-test:
  cdc-agents-stream-test-sub:
